/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package rfid;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.*;
import java.time.LocalDate;
import javax.swing.Timer;
import javax.swing.table.DefaultTableModel;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

/**
 *
 * @author ERNESTO
 */
public class ContadorRFID extends javax.swing.JFrame {

    /**
     * Creates new form ContadorRFID
     */
    public ContadorRFID() {               
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTextFieldCantTotal = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableModelos = new javax.swing.JTable();
        jTextField2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setSize(new java.awt.Dimension(1366, 768));

        jTextFieldCantTotal.setFont(new java.awt.Font("Tahoma", 1, 450)); // NOI18N
        jTextFieldCantTotal.setForeground(new java.awt.Color(153, 0, 0));
        jTextFieldCantTotal.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextFieldCantTotal.setText("0");
        jTextFieldCantTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldCantTotalActionPerformed(evt);
            }
        });

        jTableModelos.setFont(new java.awt.Font("Tahoma", 1, 100)); // NOI18N
        jTableModelos.setForeground(new java.awt.Color(153, 0, 0));
        jTableModelos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "MODELOS", "CANTIDAD"
            }
        ));
        jTableModelos.setToolTipText("");
        jTableModelos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableModelos.setGridColor(new java.awt.Color(153, 0, 0));
        jTableModelos.setRowHeight(100);
        jTableModelos.setSelectionBackground(new java.awt.Color(204, 204, 204));
        jScrollPane1.setViewportView(jTableModelos);
        if (jTableModelos.getColumnModel().getColumnCount() > 0) {
            jTableModelos.getColumnModel().getColumn(1).setMinWidth(120);
            jTableModelos.getColumnModel().getColumn(1).setPreferredWidth(120);
            jTableModelos.getColumnModel().getColumn(1).setMaxWidth(120);
        }

        jTextField2.setFont(new java.awt.Font("Tahoma", 1, 50)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(153, 0, 0));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("ALMACEN DM");
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField2, javax.swing.GroupLayout.DEFAULT_SIZE, 686, Short.MAX_VALUE)
                    .addComponent(jTextFieldCantTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 674, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextFieldCantTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 691, Short.MAX_VALUE))
            .addComponent(jScrollPane1)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public  void getSumCantidad(){
        int sum = 0;
        /*Se recorren todas las filas de la tabla para ir sumando
          las cantidades de la columna cantidad
        */
        if (jTableModelos.getRowCount()>0){
            for(int i=0;i < jTableModelos.getRowCount();i++){
                if (jTableModelos.getValueAt(i, 1)!=null) {
                    sum = sum + Integer.parseInt(jTableModelos.getValueAt(i, 1).toString());            
                }                
            }
        }
                
        
        //Se indica el total en el campo de texto
        jTextFieldCantTotal.setText(Integer.toString(sum));
    }
    public void Refrescar() {                                          
        // TODO add your handling code here:
        try {
             //Fecha del sistema
             DateTimeFormatter dtf      = DateTimeFormatter.ofPattern("dd/MM/yyyy");
             DateTimeFormatter dtf_hour = DateTimeFormatter.ofPattern("HH:mm");	     
             
             String qry = "SELECT m.nombre_lacado  as MODELO, " +
                          "       COUNT(e.id)      as CANTIDAD    " +
                          "FROM   t_lecturas_rfid    t,  " +
                          "       t_etiquetas_rfid   e,  " +
                          "       li_ped_cli_velneo  li, " +
                          "       t_modelos_velneo   m   " +
                          "WHERE  t.ip_lector_rfid   = '192.168.0.193' " +
                          "AND    t.fecha            ='"+dtf.format(LocalDate.now())+"' "+
                          "AND    t.hora             >'"+dtf_hour.format(LocalDateTime.now().minusMinutes(1))+"' " +
                          "AND    t.serie_tag        = e.serie_tag " +
                          "AND    e.pedidosclien     = li.pedidosclien " +
                          "AND    e.codigo           = li.codigo " +
                          "AND    li.cod_modelo_antiguo = m.codigo " +
                          "GROUP BY  m.nombre_lacado ";
             //Para establecer el modelo al JTable
             DefaultTableModel modelo = new DefaultTableModel();
            
             //Para conectarnos a nuestra base de datos
             DriverManager.registerDriver(new org.postgresql.Driver());
             Connection conexion = DriverManager.getConnection("jdbc:postgresql://192.168.xxx.xxx/xxxxxx", "xxxxxxx", "xxxxxxx");
             //Para ejecutar la consulta
             Statement s = conexion.createStatement();
             //Ejecutamos la consulta que escribimos en la caja de texto
             //y los datos lo almacenamos en un ResultSet
             ResultSet rs = s.executeQuery(qry);
             //Obteniendo la informacion de las columnas que estan siendo consultadas
             ResultSetMetaData rsMd = rs.getMetaData();
             //La cantidad de columnas que tiene la consulta
             int cantidadColumnas = rsMd.getColumnCount();
             //Establecer como cabezeras el nombre de las colimnas
              //if (jTableModelos.getColumnModel().getColumnCount() > 0) {
                //jTableModelos.getColumnModel().getColumn(1).setMinWidth(120);
                //jTableModelos.getColumnModel().getColumn(1).setPreferredWidth(120);
                //jTableModelos.getColumnModel().getColumn(1).setMaxWidth(120);
            //}
             for (int i = 1; i <= cantidadColumnas; i++) {
              modelo.addColumn(rsMd.getColumnLabel(i));
             }
             //Creando las filas para el JTable
             while (rs.next()) {
              Object[] fila = new Object[cantidadColumnas];
              for (int i = 0; i < cantidadColumnas; i++) {
                fila[i]=rs.getObject(i+1);
              }
              modelo.addRow(fila);
             }
             
             jTableModelos.setModel(modelo);
             if (jTableModelos.getColumnModel().getColumnCount() > 0) {
                 jTableModelos.getColumnModel().getColumn(1).setMinWidth(120);
                 jTableModelos.getColumnModel().getColumn(1).setPreferredWidth(120);
                 jTableModelos.getColumnModel().getColumn(1).setMaxWidth(120);
              }
             
             rs.close();
             conexion.close();
             getSumCantidad();
        } catch (Exception ex) {
             ex.printStackTrace();
        }
    }     
    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextFieldCantTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldCantTotalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldCantTotalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ContadorRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ContadorRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ContadorRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ContadorRFID.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
         ContadorRFID contRFID = new ContadorRFID();
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                contRFID.setVisible(true);
                //Ejecucion cada tres segundos
                Timer timer = new Timer (3000, new ActionListener () 
                {                     
                    @Override
                    public void actionPerformed(ActionEvent e) 
                    { 
                        // Aquí el código que queramos ejecutar cada tres segundos
                        contRFID.Refrescar();
                    } 
                }); 
                timer.start();
            }
        });        
    }
        

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableModelos;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextFieldCantTotal;
    // End of variables declaration//GEN-END:variables
}
